version: "3"

services:
  gpt:
    image: ghcr.io/boriselec/chatgpt-web:fork
    container_name: gpt
    logging:
      driver: local
      options:
        max-file: "20"
    environment:
      - OPENAPI_KEY=${OPENAPI_KEY}
      - API_BASE=https://api.openai.com
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=${LETSENCRYPT_URL}
      - VALIDATION=http
      - EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./swag/config:/config
    ports:
      - "443:443"
      - "80:80"  # Required for HTTP validation